function tracer(F1,F2)
% Illustre graphiquement l'addition de deux
% vecteur libres F1 et F2 dans le plan.
close all; axis equal; hold on; grid on;
gris = [0.8,0.8,0.8]; set(gca,'Color',gris);
R = F1 + F2;

%% Étape 1
% En traçant les vecteurs comme des segments de
% droite, Matlab détermine automatiquement la
% clôture de la figure.

% Vecteurs F1+F2
X = [0,F1(1),R(1),R(1)-F1(1),0];
Y = [0,F1(2),R(2),R(2)-F1(2),0];
h = plot(X,Y); set(h,'Color',gris);

% On ajuste un peu
Cloture = round(axis + [-0.5 +0.5 -0.5 +0.5]);
close (gcf)

%% Étape 2

set(gca,'Color',gris);
axis equal; hold on; axis(Cloture); grid on;

% Vecteur F2
Vecteur(Cloture,F2,F1,'r');
text(F1(1)+F2(1)/2,F1(2)+F2(2)/2,' F_2 ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

%% Autre portion du parallélogramme

% Vecteur F2
Vecteur(Cloture,F2,[0,0],'r');
text(F2(1)/2,F2(2)/2,' F_2 ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

% Vecteur F1
Vecteur(Cloture,F1,[0,0],'b');
text(F1(1)/2,F1(2)/2,' F_1 ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

%% Autre portion du parallélogramme

% Vecteur F1
Vecteur(Cloture,F1,F2,'b');
text(F2(1)+F1(1)/2,F2(2)+F1(2)/2,' F_1 ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

% Vecteur R
Vecteur(Cloture,R,[0,0],'y');
text(R(1)/2,R(2)/2,' R ',...
   'FontWeight','bold','FontSize',16,...
   'BackGroundColor',gris,...
   'EraseMode','background');
title('R  =  F_1 + F_2',...
   'FontWeight','bold','FontSize',12)

norme = norm(R);
% angle selon la convention de atan2
theta = atan2(R(2),R(1))*180/pi;

xlabel([...
   'F_1= ',num2str(F1(1)),'i, ',...
   num2str(F1(2)),'j,   ',...
   'F_2= ',num2str(F2(1)),'i, ',...
   num2str(F2(2)),'j,   ',...
   'R= ',num2str(R(1)),'i, ',...
   num2str(R(2)),'j,  norme = ',...
   num2str(norme,'%.1f'),',  ',...
   '\theta = ',num2str(theta,'%.1f'),...
   '°'],'FontSize',12)