% Écrire
% >> res200 pour le faire afficher.
msgbox(['ABC de Matlab :',char(10),...
   '  >> doc abc : guide d''initiation',char(10),...
   'Lecture :',char(10),...
   '   >> doc input : lecture à l''écran',char(10),...
   '   >> doc load : lecture de fichiers,  ex. : T= load( ''xyz.dat'' )',char(10),...
   '   >> doc xlsread : lecture d''un fichier Excel',char(10),...
   'Écriture',char(10),...
   '   >> doc plot : affichage d''un graphique',char(10),...
   '   >> doc punct : effet du point-virgule',char(10),...
   '   >> doc disp  ex.: disp( [ ''Contrainte est '',num2str(sigma),'' MPa'' ] )',char(10),...
   '   >> doc fprintf : écriture formatée. Suggestion pour une matrice:',char(10),...
   '         for i=1:n_rangées et boucle implicite pour les colonnes.',char(10),...
   'Opérateurs',char(10),...
   '   >> help +  : description des opérateurs',char(10),...
   '   >> doc aritm  : description des opérateurs arithmétiques',char(10),...
   '   >> doc precedence  : priorité des opérateurs',char(10),...
   'Structures de contrôle',char(10),...
   '   >> doc if : décision, {Aussi} >> doc end : terminaison',char(10),...
   '   >> doc relop : opérateurs <= < == ~= >= >,  & | ~',char(10),...
   '   >> doc for : boucle comptée,  le nombre de cycles est connu',char(10),...
   '   >> doc while : boucle à fin conditionnelle',char(10),...
   'Variables',char(10),...
   '   >> doc variable  : caractéristiques et nom des variables',char(10),...
   '   >> doc colon  : spécification d''éléments de tableau',char(10),...
   '   >> doc punct  : utilisation des symboles de ponctuation',char(10),...
   '   >> doc linspace  : génération des valeurs entre des bornes',char(10),...
   '   >> doc size (ou >> doc length) :  dimension d''un tableau',char(10),...
   '   >> doc whos  : liste des variables en mémoire',char(10),...
   '   >> doc sym  :  création d''objets de type symbolique',char(10),...
   'Outils de gestions - Organiser un programme',char(10),...
   '   >> doc general  : dir, cd, which, save, format, edit',char(10),...
   '   >> doc function : script, fonction et sous-fonctions'],...
   'res200 - résumé');
