function tracer(Va,Vb)
% Illustre graphiquement l'addition de deux
% vecteur libres Va et Vb dans le plan.
close all; axis equal; hold on; grid on;
gris = [0.8,0.8,0.8]; set(gca,'Color',gris);
Vr = Va + Vb;

%% Étape 1
% En traçant les vecteurs comme des segments de
% droite, Matlab détermine automatiquement la
% clôture de la figure.

% Vecteurs Va+Vb
plot([0,Va(1),Vr(1)],[0,Va(2),Vr(2)]);
% On ajuste un peu
Cloture = round(axis + [-0.5 +0.5 -0.5 +0.5]);

%% Étape 2
figure(2);
set(gca,'Color',gris);
axis equal; hold on; axis(Cloture); grid on;
% Vecteur Va
Vecteur(Cloture,Va,[0,0],'b');
text(Va(1)/2,Va(2)/2,' V_a ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

% Vecteur Vb
Vecteur(Cloture,Vb,Va,'r');
text(Va(1)+Vb(1)/2,Va(2)+Vb(2)/2,' V_b ',...
   'FontWeight','bold','FontSize',14,...
   'BackGroundColor',gris,...
   'EraseMode','background');

% Vecteur Vr
Vecteur(Cloture,Vr,[0,0],'y');
text(Vr(1)/2,Vr(2)/2,' V_r ',...
   'FontWeight','bold','FontSize',16,...
   'BackGroundColor',gris,...
   'EraseMode','background');
title('V_r  =  V_a + V_b',...
   'FontWeight','bold','FontSize',12)

norme = norm(Vr);
% angle selon la convention de atan2
theta = atan2(Vr(2),Vr(1))*180/pi;

xlabel([...
   'V_a= ',num2str(Va(1)),'i, ',...
   num2str(Va(2)),'j,   ',...
   'V_b= ',num2str(Vb(1)),'i, ',...
   num2str(Vb(2)),'j,   ',...
   'V_r= ',num2str(Vr(1)),'i, ',...
   num2str(Vr(2)),'j,  norme = ',...
   num2str(norme,'%.1f'),',  ',...
   '\theta = ',num2str(theta,'%.1f'),...
   '°'],'FontSize',12)